version: "3.8"
services:
  elasticsearch-server:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - simpplr-chatbot

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-server:9200
    networks:
      - simpplr-chatbot
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch-server:
        condition: service_healthy
        restart: true
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    platform: linux/amd64
    restart: unless-stopped
    container_name: backend
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      elasticsearch-server:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health-check"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ./SimpplrChatbot:/app
    environment:
      - DEBUG_MODE=true
      - DATA_PATH=${DATA_PATH}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - INDEX_NAME=${INDEX_NAME}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - LLM_MODEL=${LLM_MODEL}
      - LLM_TEMPERATURE=${LLM_TEMPERATURE}
      - LLM_TOP_P=${LLM_TOP_P}
      - LLM_TOP_K=${LLM_TOP_K}
      - LLM_MAX_TOKENS=${LLM_MAX_TOKENS}
      - CHUNK_SIZE=${CHUNK_SIZE}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP}
    entrypoint: /bin/bash
    command: -c "poetry run uvicorn API.app:app --reload --host 0.0.0.0 --port 8000"
    networks:
      - simpplr-chatbot

networks:
  simpplr-chatbot:
    external: false
